[package]
name = "chess-gui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jonathan_hallstrom_chess = { git = "https://github.com/INDA23PlusPlus/johalls-chess.git" }
ggez = "0.9.3"
mint = "0.5.9"